export const inspirationLines = [
  "You are stronger than you think.",
  "This pain will pass — and you will rise.",
  "You’ve survived 100% of your worst days so far.",
  "Some days, surviving is a victory. And you did it.",
  "You were never weak — just tired of being strong for too long.",
  "No storm lasts forever.",
  "Your tears water the seeds of your growth.",
  "You’re not alone. You’re just early in the story.",
  "Even stars need darkness to shine.",
  "You’re allowed to feel broken — that’s how light gets in.",
  "Small steps every day still move you forward.",
  "Your future needs you. Your past does not.",
  "One moment of courage can change everything.",
  "Rest is not weakness — it’s repair.",
  "You’re doing better than you think.",
  "Some of the most beautiful chapters won't have a title until much later.",
  "Your presence matters — more than you know.",
  "Healing is messy, nonlinear, and absolutely worth it.",
  "This world is better with you in it.",
  "You deserve peace, not just survival.",
  "Being soft is not a flaw — it’s a strength.",
  "It’s okay to outgrow people who don’t grow with you.",
  "You are not too much. You are exactly enough.",
  "People who drained you don't define you.",
  "You are allowed to protect your energy.",
  "Hope doesn’t mean ignoring pain — it means believing in more.",
  "There’s bravery in still trying.",
  "Scars mean you healed, not that you failed.",
  "Kindness is never wasted, even if it’s not returned.",
  "You’re allowed to be a masterpiece and a work in progress.",
  "It’s okay to let go of what hurts, even if it once felt safe.",
  "You’re not lost — you’re just becoming.",
  "Grief is love with nowhere to go.",
  "You can be proud of yourself just for making it this far.",
  "You are not a burden — your feelings are valid.",
  "Not everyone will understand you. That’s okay.",
  "Boundaries are a form of self-respect.",
  "You’re not hard to love — you just haven’t found the right people yet.",
  "Even when you feel invisible, you still matter.",
  "You don’t need permission to rest.",
  "You’re not broken — you’re building.",
  "You were never meant to stay small.",
  "Gentleness with yourself is radical.",
  "You are not your mistakes.",
  "You deserve softness, not sharpness.",
  "You’ve already made it through so much — keep going.",
  "The person you’re becoming is proud of you.",
  "Peace looks good on you.",
  "Your dreams are not too big.",
  "There is no shame in starting over.",
  "You’re more resilient than you feel right now.",
  "Silence is not emptiness — it’s space to heal.",
  "You’re not behind — you’re on your own timeline.",
  "You don’t have to prove your pain.",
  "You deserve love without conditions.",
  "Not being okay is not a failure.",
  "You are worthy, always.",
  "Your journey is valid, even when it's invisible.",
  "No one else has your soul. That matters.",
  "It’s okay to walk away from chaos.",
  "You’re doing the best you can with what you have.",
  "You are not too late.",
  "There is strength in asking for help.",
  "You can rebuild from here.",
  "Letting go is also a form of love.",
  "Joy will find you again.",
  "You don’t have to explain your boundaries.",
  "Even the moon goes through phases.",
  "The best chapters often follow the worst endings.",
  "You are enough — just as you are.",
  "The heaviness you carry isn’t yours forever.",
  "One breath at a time is enough.",
  "You’re not stuck — you’re growing roots.",
  "It’s okay to rewrite your story.",
  "You’re not too sensitive — you’re deeply human.",
  "Tears are a sign of release, not weakness.",
  "What you feel is real.",
  "Pain is a signal — not your identity.",
  "Your feelings deserve space.",
  "You’re already enough.",
  "Being tired doesn’t mean you’re not strong.",
  "You’re still here — and that’s something.",
  "Time doesn’t heal all, but it softens the edges.",
  "You are seen. Even when you feel invisible.",
  "Your softness is not your weakness — it’s your superpower.",
  "It's okay to rest before you're exhausted.",
  "Healing is not linear.",
  "You are allowed to need.",
  "This feeling is not forever.",
  "Even darkness has stars.",
  "You are becoming someone you're proud of.",
  "Hope lives in small moments.",
  "You are worth showing up for.",
  "Even when it’s hard to believe — you're still worthy.",
  "One kind word can change your whole day — say it to yourself.",
  "You can be your own safe space.",
  "There is still beauty here.",
  "You're learning, not failing.",
  "You are not too far gone.",
  "You still get to try again.",
  "You are not what they did to you.",
  "You can rest. The world will wait.",
  "Every sunrise is a new beginning.",
  "You are here — and that is enough.",
  "Peace is possible, even in pain.",
  "You’re not defined by your past.",
  "You are loved, even if you don’t feel it right now.",
  "You are worth fighting for.",
  "Your light hasn't gone out — it's just resting.",
  "You are becoming the person you needed.",
  "Give yourself the grace you give others.",
  "You're not failing. You're finding your way.",
  "Keep breathing. That’s enough for today.",
  "The hard days don't erase the good ones.",
  "You're more than your pain.",
  "You're allowed to take up space.",
  "There’s hope even here.",
  "You matter more than your mind is telling you.",
  "You don’t owe strength all the time.",
  "Your softness deserves protection, not punishment.",
  "Even the darkest night ends in dawn.",
  "You're still worthy, even when you're quiet.",
  "You are not your trauma.",
  "You don't have to carry it all alone.",
  "You deserve people who speak life into you.",
  "You are allowed to ask for space.",
  "You're not being dramatic — you're being real.",
  "Even broken crayons color.",
  "You are lovable, even on your worst days.",
  "You’re not behind — you’re just on a different path.",
  "This pain is temporary — your growth is not.",
  "You still belong.",
  "Your worth is not up for debate.",
  "You don’t have to earn rest.",
  "You can feel afraid and still move forward.",
  "You’re not too much — you’re enough with layers.",
  "Your existence is not an accident.",
  "You are not alone in this struggle.",
  "The best is still ahead.",
  "Even if you don’t believe it now — it will get better.",
  "You’re not what they said you were.",
  "Your story is not over.",
  "You are still becoming who you’re meant to be.",
  "You are deeply needed in this world.",
  "You are not a failure. You are in formation.",
  "Even if all you did today was breathe — that's okay.",
  "You were never alone — just unheard. I'm listening now."
];
